"""add updated column to the agent runs table 

Revision ID: c05dcce58f4b
Revises: 61bdcad6f5ef
Create Date: 2026-08-31 17:05:54.233261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05dcce58f4b'
down_revision: Union[str, Sequence[str], None] = '61bdcad6f5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('agent_runs_conversation_id_key'), 'agent_runs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('agent_runs_conversation_id_key'), 'agent_runs', ['conversation_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('agent_runs', 'updated_at')
    # ### end Alembic commands ###
