"""add last message id to memory table

Revision ID: d2d0e0182358
Revises: c05dcce58f4b
Create Date: 2026-09-01 13:24:27.997083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d0e0182358'
down_revision: Union[str, Sequence[str], None] = 'c05dcce58f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('last_message_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'memories', ['conversation_id'])
    op.create_foreign_key(None, 'memories', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_constraint(None, 'memories', type_='unique')
    op.drop_column('memories', 'last_message_id')
    # ### end Alembic commands ###
