"""test

Revision ID: f749dd3417b0
Revises: d5a0717ac301
Create Date: 2026-08-27 20:09:25.184476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f749dd3417b0'
down_revision: Union[str, Sequence[str], None] = 'd5a0717ac301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company_schema_mappings', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_schema_mappings', type_='unique')
    # ### end Alembic commands ###
